apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shopk8s.fullname" . }}-jwt
  labels:
    {{- include "shopk8s.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ required ".Values.jwt.secret is required" .Values.jwt.secret | quote }}
{{- if .Values.postgres.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shopk8s.fullname" . }}-postgres
  labels:
    {{- include "shopk8s.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  database: {{ .Values.postgres.auth.database | quote }}
  username: {{ .Values.postgres.auth.username | quote }}
  password: {{ .Values.postgres.auth.password | quote }}
{{- end }}
